{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aequor-service.serviceAccountName" . }}
  labels:
    {{- include "aequor-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  # IRSA: eks.amazonaws.com/role-arn is set here (settlement -> aequor-app role).
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
